version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "REPLACED_DURING_DEPLOYMENT"
        LoadBalancerInfo:
          ContainerName: "portfolio"
          ContainerPort: 3000
