version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 288761729262.dkr.ecr.eu-central-1.amazonaws.com
      - REPOSITORY_URI=288761729262.dkr.ecr.eu-central-1.amazonaws.com/portfolio-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - aws ecs describe-task-definition --task-definition portfolio-task --query taskDefinition > taskdef.json
      - sed -i -e "s|<IMAGE>|$REPOSITORY_URI:$IMAGE_TAG|g" taskdef.json
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      - aws ecs describe-task-definition --task-definition portfolio-task --query "taskDefinition.containerDefinitions[0].name" --output text > container-name.txt
      - export CONTAINER_NAME=$(cat container-name.txt)
      
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"portfolio","imageUri":"%s"}]' 288761729262.dkr.ecr.eu-central-1.amazonaws.com/portfolio-app:latest > imagedefinitions.json
      - echo "Container name is $CONTAINER_NAME"
      - cat imagedefinitions.json
      - cat taskdef.json
artifacts:
  files: 
    - imagedefinitions.json
    - appspec.yml
    - taskdef.json
